apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: api
    servicePort: 80
  rules:
    - host: foo.mydomain.com
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 80